local precache = util.PrecacheModel

precache("models/player/humans/modern/male/male_01.mdl")
precache("models/player/humans/modern/male/male_02.mdl")
precache("models/player/humans/modern/male/male_03.mdl")
precache("models/player/humans/modern/male/male_04.mdl")
precache("models/player/humans/modern/male/male_05.mdl")
precache("models/player/humans/modern/male/male_06.mdl")
precache("models/player/humans/modern/male/male_07.mdl")
precache("models/player/humans/modern/male/male_09.mdl")
precache("models/player/humans/modern/male/shared/male_01.mdl")
precache("models/player/humans/modern/male/shared/male_02.mdl")
precache("models/player/humans/modern/male/shared/male_03.mdl")
precache("models/player/humans/modern/male/shared/male_04.mdl")
precache("models/player/humans/modern/male/shared/male_05.mdl")
precache("models/player/humans/modern/male/shared/male_06.mdl")
precache("models/player/humans/modern/male/shared/male_07.mdl")
precache("models/player/humans/modern/male/shared/male_09.mdl")
precache("models/player/humans/modern/male/police/male_01.mdl")
precache("models/player/humans/modern/male/police/male_02.mdl")
precache("models/player/humans/modern/male/police/male_03.mdl")
precache("models/player/humans/modern/male/police/male_04.mdl")
precache("models/player/humans/modern/male/police/male_05.mdl")
precache("models/player/humans/modern/male/police/male_06.mdl")
precache("models/player/humans/modern/male/police/male_07.mdl")
precache("models/player/humans/modern/male/police/male_09.mdl")
precache("models/player/humans/modern/female/female_01.mdl")
precache("models/player/humans/modern/female/female_02.mdl")
precache("models/player/humans/modern/female/female_03.mdl")
precache("models/player/humans/modern/female/female_04.mdl")
precache("models/player/humans/modern/female/female_05.mdl")
precache("models/player/humans/modern/female/female_06.mdl")
precache("models/player/humans/modern/female/shared/female_01.mdl")
precache("models/player/humans/modern/female/shared/female_02.mdl")
precache("models/player/humans/modern/female/shared/female_03.mdl")
precache("models/player/humans/modern/female/shared/female_04.mdl")
precache("models/player/humans/modern/female/shared/female_05.mdl")
precache("models/player/humans/modern/female/shared/female_06.mdl")
precache("models/player/urban.mdl")

-- Vehicles
precache("models/tdmcars/sl65amg.mdl")
precache("models/tdmcars/mas_ghibli.mdl")
precache("models/tdmcars/zondac12.mdl")
precache("models/tdmcars/skyline_r34.mdl")
